name: GitHub Actions Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Copy code
        uses: actions/checkout@v4

      - name: "List what's inside"
        run: ls

      - name: "Install Java"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: "Verify installation"
        run: |
          java -version
          mvn -version

      - name: "Build Application"
        run: mvn clean package

      - name: "Test Application"
        run: mvn test
