name: GitHub Actions Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Copy code
        uses: actions/checkout@v4

      - name: "List what's inside"
        run: ls
